### ISSUE TITLE
poro dont start the streams

### ISSUE THREAD

**Issue by 0withoutface0** [LeagueOfPoro/EsportsCapsuleFarmer#12] opened 2022-07-07 23:38 UTC
poro succesfully logs in and then it displays that 0 new matches
Is this can be a problem with the automatic language on the site? (hungarian)
thanks for help!
![kép](https://user-images.githubusercontent.com/97801778/177888635-a4baa3f3-edd8-4168-81db-91ad542eb364.png)
![kép](https://user-images.githubusercontent.com/97801778/177888658-19d18a79-ec3e-4abd-b2b8-6a1881a5d121.png)

**Comment by 0withoutface0** [comment] 2022-07-07 23:42
that was the problem i think! I will try to put a plus step in the program to set the language to "english na"
![kép](https://user-images.githubusercontent.com/97801778/177889070-6b8f0f06-88f9-4fa4-aa70-2940a20c0588.png)
![kép](https://user-images.githubusercontent.com/97801778/177889098-c76812ab-894e-4286-8926-6305d030263d.png)

**Comment by LeagueOfPoro** [comment] 2022-07-08 05:48
Duplicate of #9
Will be fixed after regression test

**Closed by LeagueOfPoro** 2022-07-08 05:48 UTC
Labels: duplicate
